# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Build on the oldest supported ubuntu:
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libgtk2.0-dev libprocps-dev

    - name: Build .deb package
      run: make deb
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: Debian packages
        path: '*.deb'

    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
      with:
        pkgname: gatotray
        pkgbuild: ./PKGBUILD
        commit_username: gatopeich
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        ssh_keyscan_types: rsa,ecdsa,ed25519
        test: true
